In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Covid-19 data (unsorted).csv")
copy = pd.read_csv("Covid-19 data (unsorted).csv")
data = data.sort_values(by=['county', 'state'])
copy = copy.sort_values(by=['county', 'state'])
print(len(data.index))
data.to_csv("daily count.csv", index = False)
data = pd.read_csv("daily count.csv")
copy.to_csv("daily count_copy.csv", index = False)
copy = pd.read_csv("daily count_copy.csv")
copy
#data.at[5000, 'county']

479494

             date     county           state     fips  cases  deaths
0       3/19/2020  Abbeville  South Carolina  45001.0      1       0
1       3/20/2020  Abbeville  South Carolina  45001.0      1       0
2       3/21/2020  Abbeville  South Carolina  45001.0      1       0
3       3/22/2020  Abbeville  South Carolina  45001.0      1       0
4       3/23/2020  Abbeville  South Carolina  45001.0      1       0
...           ...        ...             ...      ...    ...     ...
479489  8/24/2020    Ziebach    South Dakota  46137.0     46       0
479490  8/25/2020    Ziebach    South Dakota  46137.0     46       0
479491  8/26/2020    Ziebach    South Dakota  46137.0     46       0
479492  8/27/2020    Ziebach    South Dakota  46137.0     46       0
479493  8/28/2020    Ziebach    South Dakota  46137.0     47       0

[479494 rows x 6 columns]

In [3]:
i = 1
data['fips'] = data['fips'].fillna(-1)
while i < len(data.index):
    if data.at[i, 'county'] == data.at[i - 1, 'county'] and data.at[i, 'state'] == data.at[i - 1, 'state']:
        if (data.at[i, 'cases'] < copy.at[i - 1, 'cases']):
            data.at[i, 'cases'] = copy.at[i - 1, 'cases']
        if (data.at[i, 'deaths'] < copy.at[i - 1, 'deaths']):
            data.at[i, 'deaths'] = copy.at[i - 1, 'deaths']
        data.at[i, 'cases'] = data.at[i, 'cases'] - copy.at[i - 1, 'cases']
        data.at[i, 'deaths'] = data.at[i, 'deaths'] - copy.at[i - 1, 'deaths']
    i += 1

In [4]:
data = data.astype({'fips': int})
data["date"] = pd.to_datetime(data["date"])
data = data.sort_values(by = ['date'])
data.to_csv("daily count.csv", index = False)